In [3]:
import numpy as np 
array = np.array([10,20,30,40])
print(array*5)
print(array.shape)

[ 50 100 150 200]
(4,)


In [1]:
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
row_means = np.array([2, 5, 8])   # mean of each row, shape (3,)

NameError: name 'np' is not defined

In [2]:
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
row_means = np.array([2, 5, 8])   # mean of each row, shape (3,)

NameError: name 'np' is not defined

In [3]:
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
row_means = np.array([2, 5, 8])   # mean of each row, shape (3,)


NameError: name 'np' is not defined

In [ ]:
import numpy as np
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
row_means = np.array([2, 5, 8]) 
row_means = row_means.reshape(3,1)
print(matrix - row_means)  

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [11]:
prices = np.array([100, 200, 300, 400])
discount = 0.1
print(prices - prices * 10/100) 

[ 90. 180. 270. 360.]


In [6]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A @ B)


[[19 22]
 [43 50]]
