In [ ]:
import numpy as np

In [1]:
import numpy as np

A = np.array([[2, 0],
              [1, 3]])

B = np.array([[4, 1],
              [2, 5]])

print(A @ B)

[[ 8  2]
 [10 16]]


In [3]:
A = np.array([[1,2],[3,4],[5,6]])
print(A.T)

[[1 3 5]
 [2 4 6]]
