In [1]:
import numpy as np

In [3]:
v = np.array([[3],
          [4]])

print(v.ndim)

2


In [6]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
print(a+b)
print(a-b)
print(3*a)

[ 3  7 11]
[1 1 1]
[ 6 12 18]


In [13]:
a = np.array([3, 4])
b = np.array([1, 2])
print(np.dot(a, b))
print(np.linalg.norm(a))
print(np.dot(a, a))
print(np.linalg.norm(a) ** 2)

11
5.0
25
25.0


In [2]:
import numpy as np
A = np.array([[4, 7],
              [2, 6]])
A_inv = np.linalg.inv(A)
print(A @ A_inv)
print(np.eye(2))

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
